version: '2.1'

parameters:
  action:
    type: enum
    enum: [dev]
    default: dev
    
orbs:
  terraform: circleci/terraform@3.2.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
          backend_config_path: ./backend-config/<< pipeline.parameters.environment >>.conf
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
    working_directory: ./infrastructure
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
