version: '2.1'

parameters:
  env:
    type: enum
    enum: [dev]
    default: dev
    
orbs:
  terraform: circleci/terraform@3.2.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout:
          path: ~/repo
      - terraform/init:
          path: .
          backend_config_path: ./backend-config/dev.conf
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
    working_directory: ~/repo/infrastructure
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
